export { default as Header } from './header';
export { default as Hero } from './hero';
export { default as OtherProjects } from './otherProjects';
export { default as Footer } from './footer';
export { default as ProjectCard } from './projectCard';
export { default as Contact } from './contact';
export { default as FeaturedProjectCard } from './featuredProjectCard';
export { default as FeaturedProjects } from './featuredProjects';
export { default as About } from './about';
