export { default as About } from './about'
export { default as Contact } from './contact'
export { default as Footer } from './footer'
export { default as Header } from './header'
export { default as Main } from './main'
export { default as Project } from './project'
export { default as Skills } from './skills'